stages:
- package

package-job-1:
  stage: package
  # image: ${REGISTRY_URL}/devops/helm-kubectl-rootles:latest
  image: mbwali/helm-cmpush:latest
  tags:
  - bootstrap
  before_script:
  - helm --help
  - helm repo add --username gitlab-ci-token --password ${CI_JOB_TOKEN} ${CI_PROJECT_NAME} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
  - helm package ./charts/grader-service
  - helm cm-push grader-service-0.1.0.tgz ${CI_PROJECT_NAME} #TODO make version stub
  - helm repo list
  - helm repo update
  - helm search repo grader
