stages:
- build
- charts

variables:
  RIMAGE:      "adlsregistrydev.azurecr.io/devops/alldevops:latest" # image that is used in the runner

  #Azure
  KV:          "kv-admin-os-k8s"
  KV_SVC:      "kv-service-os-k8s"
  REGISTRY:    "adlsregistrysbx"
  SERVICE:     "k8s"

build-grader-image:
  stage: build
  environment:
    name: $CI_COMMIT_BRANCH
    action: prepare
    url: https://grader.k8s.$CI_COMMIT_BRANCH.austrianopensciencecloud.org
  tags: [demo,dind]
  only:
    changes:
      - ./Dockerfile_service
  before_script:
  - export targetname="${REGISTRY}.azurecr.io/grader-service:latest"
  - echo $targetname
  script:
  # build image
  - docker build -t ${targetname} -f Dockerfile_service .

  # login to az & docker
  - tok=$(docker run mcr.microsoft.com/azure-cli /bin/bash -c "az login --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)"  --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID > /dev/null; az acr login -n adlsregistrysbx --expose-token --output tsv --query accessToken")
  - docker login adlsregistrysbx.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password $tok 

  # push image
  - docker push ${targetname}
  
  after_script:
  # logout
  - docker logout
  - az logout


trigger_charts_package:
  stage: charts
  trigger:
    include: charts/grader-service/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - charts/grader-service/**/*
