stages:
- build
- charts


build-grader-image:
  stage: build
  tags:
  - bootstrap
  only:
    changes:
      - ./Dockerfile_service
  before_script:
  - docker login -u ${REGISTRY_USER} -p ${REGISTRY_KEY} ${REGISTRY_URL}
  script:
  - echo "TODO:add building image command"
  - echo "TODO:push image to registry command"


trigger_charts_package:
  stage: charts
  trigger:
    include: charts/grader-service/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - charts/grader-service/**/*
