# Copyright (c) 2022, TU Wien
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

stages:
- build

default:
  image: ${CI_REGISTRY}/ci/ci-docker-image:latest

variables:
  IMAGE: ${CI_REGISTRY}/grader/grader-service
  TAG: ${CI_COMMIT_SHORT_SHA}

build-grader-service-image:
  stage: build

  only:
    changes:
      - ./Dockerfile
      - ./grader_service/*/**
  
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker build -t ${IMAGE}:${TAG} .

  after_script:
    - docker logout