version: "2.2"
services:

  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile_lab
    image: "grader-lap:latest"
    ports:
      - "8000:8000"
    depends_on:
      - grader_service


  grader_service:
    build:
      context: .
      dockerfile: Dockerfile_service
    image: "grader_service:latest"
    ports:
      - "4010:4010"
