name: jupyter-dev
channels:
- defaults
dependencies:
- _libgcc_mutex=0.1=main
- alembic=1.6.4
- appdirs=1.4.4
- async_generator=1.10
- attrs=21.2.0
- babel=2.9.1
- backcall=0.2.0
- black=19.10b0
- bleach=4.0.0
- certipy=0.1.3
- click=8.0.1
- configurable-http-proxy=4.0.1=node14_0
- decorator=5.0.9
- defusedxml=0.7.1
- entrypoints=0.3
- idna=2.10
- importlib_metadata=3.10.0
- ipykernel=5.3.4
- ipython_genutils=0.2.0
- isort=5.9.2
- jinja2=3.0.1
- json5=0.9.6
- jsonschema=3.2.0
- jupyter-packaging=0.7.12
- jupyter_client=6.1.12
- jupyter_telemetry=0.1.0
- jupyterlab_pygments=0.1.2
- jupyterlab_server=2.6.1
- mako=1.1.4
- mccabe=0.6.1
- mypy_extensions=0.4.3
- nbclassic=0.2.6
- nbclient=0.5.3
- nbformat=5.1.3
- nest-asyncio=1.5.1
- oauthlib=3.1.1
- packaging=21.0
- pamela=1.0.0
- parso=0.7.0
- pathspec=0.7.0
- pexpect=4.8.0
- pickleshare=0.7.5
- pip
- prometheus_client=0.11.0
- prompt-toolkit=3.0.17
- ptyprocess=0.7.0
- pycparser=2.20
- pygments=2.9.0
- pyopenssl=20.0.1
- pyparsing=2.4.7
- python-dateutil=2.8.2
- python-editor=1.0.4
- python-json-logger=2.0.1
- pytz=2021.1
- requests=2.25.1
- send2trash=1.5.0
- six=1.16.0
- testpath=0.5.0
- toml=0.10.2
- traitlets=5.0.5
- typing_extensions=3.10.0.2
- urllib3=1.26.6
- wcwidth=0.2.5
- webencodings=0.5.1
- wheel=0.36.2
- zipp=3.5.0
- pip:
- anyio==3.2.1
- deprecation==2.1.0
- docker==5.0.0
- dockerspawner==12.1.0
- docopt==0.6.2
- escapism==1.0.1
- gitdb==4.0.7
- gitpython==3.1.17
- iniconfig==1.1.1
- ipywidgets==7.6.3
- jupyter==1.0.0
- jupyter-console==6.4.0
- jupyter-server==1.9.0
- jupyterhub-systemdspawner==0.15.0
- jupyterlab==3.1.9
- jupyterlab-widgets==1.0.0
- nbconvert==5.6.1
- oauthenticator==14.1.0
- pep517==0.12.0
- pip==21.3
- pip-compile-multi==2.4.2
- pip-tools==6.4.0
- pipreqs==0.4.10
- pluggy==0.13.1
- py==1.10.0
- pytest==6.2.4
- qtconsole==5.1.1
- qtpy==1.10.0
- rapidfuzz==1.5.0
- requests-unixsocket==0.2.0
- smmap==4.0.0
- tomli==1.2.1
- tomlkit==0.7.0
- toposort==1.7
- tornado-sqlalchemy==0.7.0
- websocket-client==1.1.0
- widgetsnbextension==3.5.1
- yarg==0.1.9
- cryptography==3.4.7
- brotlipy==0.7.0
- jedi==0.17.2
- pyzmq==20.0.0
- pylint==2.7.4
- icu==68.1
- krb5==1.19.2
- tk==8.6.10
- markupsafe==2.0.1
- typed-ast==1.4.3
- jupyter_core==4.7.1
- pandocfilters==1.4.3
- lazy-object-proxy==1.6.0
- notebook==6.4.0
- setuptools==52.0.0
- sniffio==1.2.0
- chardet==4.0.0
- ca-certificates==2021.7.5
- libgomp==9.3.0
- libuv==1.40.0
- cffi==1.14.6
- certifi==2021.5.30
- greenlet==1.1.0
- wrapt==1.12.1
- pycurl==7.43.0.6
- ruamel.yaml.clib==0.2.2
- zeromq==4.3.4
- libsodium==1.0.18
- openssl==1.1.1l
- regex==2021.8.3
- pyjwt==2.1.0
- mistune==0.8.4
- libssh2==1.9.0
- argon2-cffi==20.1.0
- ruamel.yaml==0.16.12
- zlib==1.2.11
- terminado==0.9.4
- libedit==3.1.20210216
- libcurl==7.71.1
- importlib-metadata==3.10.0
- sqlalchemy==1.4.22
- tornado==6.1
- ipython==7.22.0
- libgcc-ng==9.3.0
- blinker==1.4
- pysocks==1.7.1
- ncurses==6.2
- pyrsistent==0.17.3
- astroid==2.5
- libffi==3.3
- readline==8.1
- ld_impl_linux-64==2.35.1
