apiVersion: apps/v1
kind: Deployment
metadata:
  name: grader-service
  labels:
    app: jupyterhub
    component: grader-service
    release: jupyterhub
  namespace: default
spec:
  selector:
    matchLabels:
      app: jupyterhub
      component: grader-service
      release: jupyterhub
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyterhub
        component: grader-service
        release: jupyterhub
        hub.jupyter.org/network-access-hub: "true"
        hub.jupyter.org/network-access-proxy-http: "true"
    spec:
      containers:
      - name: grader-service
        image: s210.dl.hpc.tuwien.ac.at/grader/grader-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4010
          name: service-port
          protocol: TCP
        env:
          - name: JUPYTERHUB_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: hub
                key: hub.services.grader.apiToken
          - name: JUPYTERHUB_API_URL
            value: 'http://hub:8081/hub/api'
          - name: GRADER_SERVICE_PORT
            value: "4010"
          - name: JUPYTERHUB_BASE_URL
            value: '/'
          - name: JUPYTERHUB_SERVICE_NAME
            value: 'grader'
---
apiVersion: v1
kind: Service
metadata:
  name: grader-service
  namespace: default
  labels:
    app: jupyterhub
    component: grader-service
    release: jupyterhub
spec:
  ports:
  - port: 4010
    protocol: TCP
  selector:
    app: jupyterhub
    component: grader-service
    release: jupyterhub
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grader-service
  namespace: default
spec:
  egress:
  - ports:
    - port: 8081
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: jupyterhub
          component: hub
          release: jupyterhub
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.254/32
  ingress:
  - from:
    - podSelector:
        matchLabels:
          hub.jupyter.org/network-access-singleuser: "true"
    ports:
    - port: service-port
      protocol: TCP
  podSelector:
    matchLabels:
      app: jupyterhub
      component: grader-service
      release: jupyterhub
  policyTypes:
  - Ingress
  - Egress
