hub:
  services:
    grader:
      url: "http://grader-service:4010"
      oauth_client_id: "grader"
singleuser:
  image:
    name: s210.dl.hpc.tuwien.ac.at/grader/grader-notebook-minimal
    tag: arm
  extraEnv:
    GRADER_HOST_URL: "grader-service"