openapi: '3.0.2'
info:
  title: Grader API
  version: '0.1'
servers:
    - url: /services/mock
      description: relative path to mock

###### Tags of API endpoints
tags:
- name: "Lectures"
  description: "Available lectures"
- name: "Assignments"
  description: Assignments of a lecture
- name: "Submissions"
  description: View submissions of an assignment
- name: "Grading"
  description: Manage the grading and feedback of assignments (Instructor)


paths:
  /lectures:
    $ref: './openapi/paths.yml#/lectures'

  /lectures/{lect_id}:
    $ref: './openapi/paths.yml#/lecturesById'

  /lectures/{lect_id}/assignments:
    $ref: './openapi/paths.yml#/assignments'

  # get id has no query params for grader 
  /lectures/{lect_id}/assignments/{a_id}:
    $ref: './openapi/paths_grader.yml#/assignmentsById'
  
  /lectures/{lect_id}/assignments/{a_id}/properties:
    $ref: './openapi/paths_grader.yml#/propertiesAssignment'

  /lectures/{lect_id}/assignments/{a_id}/submissions:
    $ref: './openapi/paths_grader.yml#/submissions'
  
  /lectures/{lect_id}/assignments/{a_id}/submissions/{s_id}:
    $ref: './openapi/paths.yml#/submissionsById'

  /lectures/{lect_id}/assignments/{a_id}/submissions/{s_id}/properties:
    $ref: './openapi/paths_grader.yml#/propertiesSubmission'

  /lectures/{lect_id}/assignments/{a_id}/grading/{s_id}/auto:
    $ref: './openapi/paths.yml#/auto'

  /lectures/{lect_id}/assignments/{a_id}/grading/{s_id}/feedback:
    $ref: './openapi/paths.yml#/feedback'
  
  /permissions:
    $ref: './openapi/paths.yml#/permissions'




